### PR TITLE
Updated PC port to the latest pret commit

### PR DESCRIPTION
**Pull request by BiffaloXIII**
With help from @NTx86.

### CODE REVIEW

**Comment by NTx86** [comment]
This is cannot be merged yet because this changes the alignment of save files, which makes it incompatible with save files from original ROM

**Comment by BiffaloXIII** [comment]
> This is cannot be merged yet because this changes the alignment of save files, which makes it incompatible with save files from original ROM

Right, you mentioned that. I'll mark is as draft in the meantime

**Comment by NTx86** [comment]
I'm really close to fixing it. I'll probably be able to send the changes soon

**Comment by BiffaloXIII** [comment]
Fix by @NTx86 added.
Ready for review.

**Pull request closed without merging**
